trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Production-Secrets
  - name: buildConfiguration
    value: 'Release'
  - name: azureSubscription
    value: 'Azure'  # Azure DevOps service connection name
  - name: backendAppName
    value: 'AngularDotNetMovies'
  - name: frontendAppName
    value: 'AngularFrontEnd'  # Name of your Static Web App resource
  - name: azureResourceGroup
    value: 'devops'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build_Backend
    displayName: 'Build .NET Backend'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build Backend'
      inputs:
        command: 'build'
        projects: 'Movies.API/Movies.API.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Backend'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/backend'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Backend Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
        ArtifactName: 'backend'

  - job: Build_Frontend
    displayName: 'Build Angular Frontend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '19.x'

    - script: |
        cd Movies.Frontend
        npm install
        npm run build -- --configuration production
      displayName: 'Install and Build Angular'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Frontend Artifact'
      inputs:
        targetPath: 'Movies.Frontend/dist/movies.frontend'
        artifact: 'frontend'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy_Backend
    displayName: 'Deploy Backend to App Service'
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Backend Artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'backend'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      displayName: 'Deploy Backend'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appType: 'webAppLinux'
        appName: '$(backendAppName)'
        package: '$(System.ArtifactsDirectory)/backend/**/*.zip'

  - job: Deploy_Frontend
    displayName: 'Deploy Frontend via Azure CLI'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Frontend Artifact'
      inputs:
        artifact: 'frontend'
        path: '$(Pipeline.Workspace)/frontend'

    - task: AzureCLI@2
      displayName: 'Upload to Azure Static Web App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az extension add --name "staticwebapp" --yes
          az staticwebapp upload \
            --name "$(frontendAppName)" \
            --resource-group "$(azureResourceGroup)" \
            --source "$(Pipeline.Workspace)/frontend" \
            --token "$(SWA_DEPLOYMENT_TOKEN)"
