name: Deploy Angular Frontend to Azure Static Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Movies.Frontend
          npm ci

      - name: Build Angular app
        run: |
          cd Movies.Frontend
          npm run build -- --configuration production

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Needed for GitHub APIs
          action: "upload"
          app_location: "Movies.Frontend"
          output_location: "dist/movies.frontend"
