name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular Frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Build
        run: |
          cd Movies.Frontend
          npm install
          npm run build -- --configuration production

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # used for GitHub integrations (e.g., PR comments)
          action: "upload"
          app_location: "Movies.Frontend/dist/movies.frontend"
          skip_app_build: true
